In [ ]:
import numpy as np

**Внимание** Во всех заданиях данной работы **запрещено** обращаться к массивам поэлементно и использовать циклы языка Python

**Задание 1.** Напишите функцию, принимающую два массива произвольных размерностей и возвращающую True тогда и только тогда, когда эти два массива поэлементно равны

In [ ]:
def task1(x, y):
    if (x.shape != y.shape):
      return False
    return all((x == y).reshape(sum(x.shape)))


a, b = np.arange(4).reshape(2,2), np.arange(4).reshape(2,2)
c, d = np.arange(4).reshape(2,2), np.arange(2, 6).reshape(2,2)
e, f = np.arange(4).reshape(2,2), np.arange(2, 6)
print(task1(a, b))
print(task1(c, d))
print(task1(e, f))

True
False
False


**Задание 2.** Напишите функцию, которая принимает на вход двумерный массив (это условие можно не проверять), и возвращает массив, в котором каждый элемент исходного массива поделен на сумму модулей элементов его строки.

Например,
для массива
$$
\left(\begin{array}{cc}
    1 & - 1 \\
    2 & 4
\end{array}\right)
$$ должен быть возвращен массив
$$
\left(\begin{array}{cc}
    \frac{1}{2} & -\frac{1}{2} \\
    \frac{1}{3} & -\frac{2}{3}
\end{array}\right)
$$

In [153]:
def task2(x):
    mod = np.sum(abs(x), axis=1)
    if (any(mod==0)):
      raise Exception("Division by zero problem")
    return x / mod.reshape(len(x), 1)


a = np.random.randint(-10, 10, size=(2,2))
print(a)
print(task2(a))

[[-6  2]
 [-8 -4]]
[[-0.75        0.25      ]
 [-0.66666667 -0.33333333]]


**Задание 3** Напишите функцию, которая принимает на вход одномереный массив и возвращает матрицу Вандермонда для элемментов этого массива.
Напомним, что матрицей Вандермонда для элементов $(x_1, x_2, \ldots, x_n)$ называется квадратная матрица порядка $n$, имеющая следующий вид
$$
\left(\begin{array}{ccccc}
1 & x_1 & x_1^2 & \ldots  & x_1^{n - 1} \\
1 & x_2 & x_2^2 & \ldots  & x_2^{n - 1} \\
1 & x_3 & x_3^2 & \ldots  & x_3^{n - 1} \\
& & \ldots & & \\
1 & x_n & x_n^2 & \ldots  & x_n^{n - 1} \\
\end{array}
\right)
$$

*Важно*: в этом задании запрещено использовать встроенную функцию `np.vander`. И код из нее тоже не надо копировать и даже творчески переписывать не стоит, для решения достаточно функций, показанных на семинаре

In [116]:
def task3(elements):
    dim = len(elements)
    powers = np.arange(0, dim)
    arr = elements.reshape(dim, 1) * np.repeat(1, dim)
    return arr**powers

a = np.random.randint(-9, 9, size=(np.random.randint(3, 10)))
print(a)
print(task3(a))

[-8 -4 -7 -9 -7]
[[   1   -8   64 -512 4096]
 [   1   -4   16  -64  256]
 [   1   -7   49 -343 2401]
 [   1   -9   81 -729 6561]
 [   1   -7   49 -343 2401]]


**Задание 4.** Напишите функцию, которая принимает на вход массив и возвращает новый массив, который получен из аргумента заменой всех отрицательных элементов на среднее значение всех положительных элементов исходного массива

In [154]:
from logging import exception
def task4(ar):
    positive = ar >= 0
    if (not len(ar[ar >= 0])):
      raise Exception("Can't calculate mean, because there're no positive numbers")
    mean = sum(ar[ar >= 0]) / len(ar[ar >= 0])
    ar[ar<0] = mean
    return ar

a = np.random.randint(-10, 10, size=(np.random.randint(5, 6)))
a = a.astype(float)
print(a)
print(task4(a))

[ -6.   1. -10.  -9.   4.]
[2.5 1.  2.5 2.5 4. ]
